//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "concerts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: Date,
    pub disambiguation: Option<String>,
    pub venue_id: i32,
    pub artist_id: i32,
    pub source: Option<String>,
    pub sort_order: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::performances::Entity")]
    Performances,
    #[sea_orm(has_many = "super::sets::Entity")]
    Sets,
    #[sea_orm(
        belongs_to = "super::venues::Entity",
        from = "Column::VenueId",
        to = "super::venues::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Venues,
}

impl Related<super::performances::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Performances.def()
    }
}

impl Related<super::sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sets.def()
    }
}

impl Related<super::venues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Venues.def()
    }
}
