//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "performances")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub segue: bool,
    pub set_id: i32,
    pub concert_id: i32,
    pub song_id: i32,
    pub artist_id: i32,
    pub songtitle_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artists::Entity",
        from = "Column::ArtistId",
        to = "super::artists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Artists,
    #[sea_orm(
        belongs_to = "super::concerts::Entity",
        from = "Column::ConcertId",
        to = "super::concerts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Concerts,
    #[sea_orm(
        belongs_to = "super::sets::Entity",
        from = "Column::SetId",
        to = "super::sets::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sets,
    #[sea_orm(
        belongs_to = "super::songs::Entity",
        from = "Column::SongId",
        to = "super::songs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Songs,
    #[sea_orm(
        belongs_to = "super::songtitles::Entity",
        from = "Column::SongtitleId",
        to = "super::songtitles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Songtitles,
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artists.def()
    }
}

impl Related<super::concerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concerts.def()
    }
}

impl Related<super::sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sets.def()
    }
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::songtitles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songtitles.def()
    }
}
