//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sets")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub unique_name: String,
    pub concert_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concerts::Entity",
        from = "Column::ConcertId",
        to = "super::concerts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Concerts,
}

impl Related<super::concerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concerts.def()
    }
}
