//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "songtitles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub is_default: bool,
    pub song_id: i32,
    #[sea_orm(unique)]
    pub slug: String,
    pub alias_for: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::songs::Entity",
        from = "Column::SongId",
        to = "super::songs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Songs,
    #[sea_orm(
        belongs_to = "super::songtitles::Entity",
        from = "Column::AliasFor",
        to = "super::songtitles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SongTitles,
}

impl Related<super::songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Songs.def()
    }
}

impl Related<super::songtitles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SongTitles.def()
    }
}
